<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mapping\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.Interop.NServiceBus" Version="9.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PdfProcessing.Infrastructure.Integration\PdfProcessing.Infrastructure.Integration.Contracts.csproj" />
    <ProjectReference Include="..\PdfProcessing.Persistence\PdfProcessing.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
